[color.bright]
black = "#5b6268"
blue = "#3071db"
cyan = "#46d9ff"
green = "#4db5bd"
magenta = "#a9a1e1"
red = "#da8548"
white = "#dfdfdf"
yellow = "#ecbe7b"

[color.cursor]
cursor = "#528bff"
text = "CellBackground"

[color.normal]
black = "#1c1f24"
blue = "#51afef"
cyan = "#5699af"
green = "#98be65"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#202328"
yellow = "#da8548"

[color.primary]
background = "#282c34"
foreground = "#bbc2cf"

[color.selection]
background = "#3e4451"
text = "CellForeground"
