import = [
    #"~/.config/alacritty/themes/themes/monokai_pro_spectrum.toml"
    #"~/.config/alacritty/themes/themes/dracula_plus.toml"
    "~/.config/alacritty/themes/themes/dracula.toml"
    #"~/.config/alacritty/themes/themes/doom_one.toml"
    #"~/.config/alacritty/themes/themes/snazzy.toml"
    #"~/.config/alacritty/themes/themes/smoooooth.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Medium"

[scrolling]
history = 10000

[shell]
program = "/bin/zsh"

[window]
dynamic_padding = false
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 5
