#!/bin/zsh

# enable color support of ls, less and man, and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    alias diff='diff --color=auto'
    alias ip='ip --color=auto'

    # Take advantage of $LS_COLORS for completion as well
    zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
    zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=    01;32:locus=01:qu    ote=01'

# some more ls aliases
if [ -x /usr/bin/exa ]; then
	alias ls='exa --color=always --group-directories-first'
	alias ll='exa -alF --color=always --group-directories-first'
	alias lg='exa -alg --color=always --group-directories-first'
	alias la='exa -al --color=always --group-directories-first'
else
	alias ll='ls -alF'
	alias la='ls -Alh'
	alias l='ls -CF'
fi

# my aliases
alias sudo='sudo '
alias vim='nvim'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias py='python3'

# config files
alias nvimrc='vim ~/.dotfiles/nvim/.config/nvim/vim-plug'
alias zshrc='vim ~/.dotfiles/zsh/.config/zsh'
alias bashrc='vim ~/.dotfiles/bash/.bashrc'
