#!/bin/zsh

# create a zkbd compatible hash;
# to add other keys to this hash, see: man 5 terminfo
typeset -A key

key[Home]=${terminfo[khome]}
key[End]=${terminfo[kend]}
key[Insert]=${terminfo[kich1]}
key[Delete]=${terminfo[kdch1]}
key[Up]=${terminfo[kcuu1]}
key[Down]=${terminfo[kcud1]}
key[Left]=${terminfo[kcub1]}
key[Right]=${terminfo[kcuf1]}
key[PageUp]=${terminfo[kpp]}
key[PageDown]=${terminfo[knp]}

# setup key accordingly
[[ -n "${key[Home]}"     ]]  && bindkey  "${key[Home]}"     beginning-of-line
[[ -n "${key[End]}"      ]]  && bindkey  "${key[End]}"      end-of-line
[[ -n "${key[Insert]}"   ]]  && bindkey  "${key[Insert]}"   overwrite-mode
[[ -n "${key[Delete]}"   ]]  && bindkey  "${key[Delete]}"   delete-char
[[ -n "${key[Up]}"       ]]  && bindkey  "${key[Up]}"       up-line-or-history
[[ -n "${key[Down]}"     ]]  && bindkey  "${key[Down]}"     down-line-or-history
[[ -n "${key[Left]}"     ]]  && bindkey  "${key[Left]}"     backward-char
[[ -n "${key[Right]}"    ]]  && bindkey  "${key[Right]}"    forward-char
[[ -n "${key[PageUp]}"   ]]  && bindkey  "${key[PageUp]}"   up-line-or-history
[[ -n "${key[PageDown]}" ]]  && bindkey  "${key[PageDown]}" down-line-or-history

# Finally, make sure the terminal is in application mode, when zle is
# active. Only then are the values from $terminfo valid.
function zle-line-init () {
    echoti smkx
}
function zle-line-finish () {
    echoti rmkx

}
zle -N zle-line-init
zle -N zle-line-finish

## bindkey ' ' magic-space                           # do history expansion on space
## bindkey '^U' backward-kill-line                   # ctrl + U
## bindkey '^[[3;5~' kill-word                       # ctrl + Supr
## bindkey '^[[3~' delete-char                       # delete
## bindkey '^[[1;5C' forward-word                    # ctrl + ->
## bindkey '^[[1;5D' backward-word                   # ctrl + <-
## bindkey '^[[5~' beginning-of-buffer-or-history    # page up
## bindkey '^[[6~' end-of-buffer-or-history          # page down
## bindkey '^[[H' beginning-of-line                  # home
## bindkey '^[[F' end-of-line                        # end
## bindkey '^[[Z' undo                               # shift + tab undo last action
## 
