#!/bin/zsh

### ARCHIVE EXTRACTION
# usage: ex <file>
ex () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1   ;;
            *.tar.gz)    tar xzf $1   ;;
            *.bz2)       bunzip2 $1   ;;
            *.rar)       unrar x $1   ;;
            *.gz)        gunzip $1    ;;
            *.tar)       tar xf $1    ;;
            *.tbz2)      tar xjf $1   ;;
            *.tgz)       tar xzf $1   ;;
            *.zip)       unzip $1     ;;
            *.Z)         uncompress $1;;
            *.7z)        7z x $1      ;;
            *.deb)       ar x $1      ;;
            *.tar.xz)    tar xf $1    ;;
            *.tar.zst)   unzstd $1    ;;
            *)           echo "'$1' cannot be extracted via ex()" ;;
            esac
    else
        echo "'$1' is not a valid file"
    fi
}

add_plugin() {
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ ! -d "$HOME/.config/zshrc.d/plugins/$PLUGIN_NAME" ]; then
        git clone "https://github.com/$1.git" "$HOME/.config/zshrc.d/plugins/$PLUGIN_NAME"
    else
        echo "Plugin already installed"
    fi
    unset PLUGIN_NAME
}

update_plugin() {
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$HOME/.config/zshrc.d/plugins/$PLUGIN_NAME" ]; then
        git clone "https://github.com/$1.git" "$HOME/.config/zshrc.d/plugins/$PLUGIN_NAME"
    else
        echo "Plugin not installed"
    fi
    unset PLUGIN_NAME
}
